{
 "title": "CIFAR_API",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API Runtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "expr": "api_runtime_secs", "legendFormat": "{{client}} {{instance}}" }
   ]
  },
  {
   "title": "Total API Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    { "expr": "api_call_counter_total", "legendFormat": "{{client}} {{instance}}" }
   ]
  },
  {
   "title": "API CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(cpu) (rate(node_cpu_seconds_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "targets": [
    { "expression": "${A}-${B}", "type": "math" }
   ]
  },
  {
   "title": "API Network I/O Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_network_receive_bytes_total[1m]))",
     "legendFormat": "network_bytes_recieved"
    },
    {
     "expr": "sum by(instance) (rate(node_network_transmit_bytes_total[1m]))",
     "legendFormat": "network_bytes_sent"
    }
   ]
  }
 ]
}